config:
subcomponents:
  fluentbit:
    config:
      extraEntries:
        output: |-
          [OUTPUT]
              Name        azure
              Match       *
              Customer_ID workspaceid
              Shared_Key  secretkey