config:
subcomponents:
  fluentbit:
    config:
      rawConfig: |-
        @INCLUDE fluent-bit-service.conf
        @INCLUDE fluent-bit-input.conf
        @INCLUDE fluent-bit-filter.conf
        @INCLUDE fluent-bit-output.conf
        [OUTPUT]
          Name        azure
          Match       *
          Customer_ID workspaceid
          Shared_Key  secretkey